name: to_do_app
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get_storage: ^2.0.3
  get: ^4.6.1
  flutter_local_notifications: ^9.2.0
  flutter_native_timezone: ^2.0.0
  intl: ^0.17.0
  google_fonts: ^2.2.0
  date_picker_timeline: ^1.2.3
  sqflite: ^2.0.2
  flutter_staggered_animations: ^1.0.0
  flutter_svg: ^1.0.3
  rxdart: ^0.27.3 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  flutter_launcher_icons: ^0.9.2

flutter_icons:
  android: true
  iso: true
  image_path: "assets/images/appicon.jpeg"

flutter:
  uses-material-design: true

  assets:
    - assets/images/person.jpeg
    - assets/images/task.svg

